# Generated by Django 3.2.4 on 2022-01-31 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat_user',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_users', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='chat_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
