# Generated by Django 3.2.5 on 2021-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210706_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
