# Generated by Django 3.2.5 on 2021-07-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_time_changed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-time_changed']},
        ),
        migrations.RemoveField(
            model_name='chat_user',
            name='is_block',
        ),
    ]
