# Generated by Django 4.0.6 on 2022-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFull', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('index', models.IntegerField(default=0)),
                ('block_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255, unique=True)),
                ('average_time', models.DecimalField(decimal_places=4, default=0, max_digits=6, max_length=10)),
                ('average_waste_space', models.DecimalField(decimal_places=4, default=0, max_digits=6, max_length=10)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
    ]
