# Generated by Django 4.0.6 on 2022-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
