# Generated by Django 4.0.6 on 2022-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_index_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('index', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('next', models.IntegerField(default=0)),
            ],
        ),
    ]
