# Generated by Django 4.0.6 on 2022-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='config',
            field=models.JSONField(null=True),
        ),
    ]
