name: django CI
env:
    MYSQL_DATABASE: moshaver_db
    MYSQL_USER: root
    MYSQL_PASSWORD: password

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: moshaver_db
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306

    # services:
    #   mysql-master:
    #     image: mysql:5.7
    #     ports:
    #       - 3306/tcp
    #     env:
    #       MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
    #       MYSQL_USER: ${{ env.MYSQL_USER }}
    #       MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
    #       MYSQL_ROOT-PASSWORD: ${{ env.MYSQL_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    
    # - name: Shutdown Ubuntu MySQL (SUDO)
    #   run: sudo service mysql stop
    
    # - name: set up mysql
    #   uses: mirromutth/mysql-action@v1.1
    #   with:
    #     mysql database: 'moshaver_db' # Optional, default value is "test". The specified database which will be create
    #     mysql root password: 'YDP8mkt@zru@mez4udh' # Required if "mysql user" is empty, default is empty. The root superuser password
    #     mysql user: 'moshaver' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
    #     mysql password: 'YDP8mkt@zru@mez4udh'
        
    - name: install python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.7
    # - name: Verify MySQL connection
    #   run: |
    #     mysql --version
    #     sudo apt-get install -y mysql-client
    #     mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"
    - name: install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: coverage report
      run: |
          pip install coverage
          coverage run manage.py test
          coverage report
    - name: django testing
      run: |
          env:
            MYSQL_DATABASE: moshaver_db
            DB_USERNAME: root
            DB_PASSWORD: password
            DB_PORT: ${{ job.services.mysql.ports[3306] }}
          python3 manage.py test
